defaultSemverRangePrefix: ""

logFilters:
  - code: YN0032
    level: discard
  - code: YN0060
    level: discard
  - code: YN0061
    level: discard
  - code: YN0062
    level: discard

npmScopes:
  saladtechnologies:
    npmAlwaysAuth: true
    npmAuthIdent: "VssSessionToken:${NPM_TOKEN}"
    npmRegistryServer: "https://pkgs.dev.azure.com/SaladTechnologies/_packaging/SaladTechnologies/npm/registry/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.4.1.cjs
