[build]
  command = "./.netlify/build.sh"
  publish = "./build/"

[build.environment]
  NODE_ENV="production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Environment variables defined when building the `main` branch.
[context.production.environment]
  NODE_ENV="production"

# Environment variables defined when building any other branch.
[context.branch-deploy.environment]
  NODE_ENV="production"

# Environment variables defined when building a pull request.
[context.deploy-preview.environment]
  NODE_ENV="production"
